name: Build and deploy .NET 9 Web app to Azure Web App - StriveUp.Web

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Build StriveUp.Web project only
        run: dotnet build StriveUp.Web/StriveUp.Web.csproj --configuration Release

      - name: Publish StriveUp.Web project only
        run: dotnet publish StriveUp.Web/StriveUp.Web.csproj --configuration Release --output ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: striveup-web-publish
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: striveup-web-publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_42954499032546A5ABE87023BBAA79C6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2CFCA205CBD749D696D088D777DFD9CD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_352AC8F4241D40C68DBE1E5E33A58BBA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "StriveUp"
          slot-name: "Production"
          package: .
