name: Build and deploy ASP.Net Core app to Azure Web App - StriveUpAPI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Build API project only
        run: dotnet build StriveUp.API/StriveUp.API.csproj --configuration Release

      - name: Publish API project only
        run: dotnet publish StriveUp.API/StriveUp.API.csproj --configuration Release --output ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: api-publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3A63181EE0404B3A962ECB1ABF1EF066 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_79106C327C1C4739A6E5E2B59E308965 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DD85200A4612419BA6C6854DDA053C5F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "StriveUpAPI"
          slot-name: "Production"
          package: .
