name: Build and deploy Azure Function App - StriveUp.Sync

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  FUNCTION_PROJECT_PATH: "StriveUp.Sync/StriveUp.Sync.csproj"
  DOTNET_VERSION: "8.0.x"

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup .NET ${{ env.DOTNET_VERSION }}"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Build Function Project"
        run: dotnet build ${{ env.FUNCTION_PROJECT_PATH }} --configuration Release

      - name: "Publish Function Project"
        run: dotnet publish ${{ env.FUNCTION_PROJECT_PATH }} --configuration Release --output ./publish

      - name: "Login to Azure"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_68F671ACA6F9428A875DDA8E5CA5B4A6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_440E0B5B8B29478384D5E2BDE3837960 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_56F68B7EDC704310A4838EED31785449 }}

      - name: "Deploy to Azure Function App"
        uses: Azure/functions-action@v1
        with:
          app-name: "SyncFunction"
          slot-name: "Production"
          package: "./publish"
